apiVersion: v1
kind: Pod
metadata:
  name: titan-pod
  labels:
    app: titan
spec:
  containers:
  - name: titan-container
    image: 917374863672.dkr.ecr.us-east-1.amazonaws.com/titan:f90f99d6da6a9961251463b910266d10ec3ea341
    ports:
    - containerPort: 80
